version: '3.8'

services:
  db_app:
    image: postgres:15-alpine
    container_name: quimio_db_app
    volumes:
      - postgres_app_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_quimio
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db_quimio" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - quimio_network

volumes:
  postgres_app_data:

networks:
  quimio_network:
    driver: bridge
