version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quimio_app_prod
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db_app:
        condition: service_healthy
    environment:
      - APP_DB_URL=postgresql+asyncpg://user:password@db_app:5432/db_quimio
      - AGHU_DB_URL=postgresql+asyncpg://user:password@db_aghu:5432/db_aghu
      - AD_SERVER=ldap://openldap_server:389
      - AD_DOMAIN=hc.gov.br
      - AD_BASEDN=dc=hc,dc=gov,dc=br
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - quimio_network_prod
      - rede_externa

  db_app:
    image: postgres:15-alpine
    container_name: quimio_db_prod
    restart: always
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_quimio
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db_quimio" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - quimio_network_prod

volumes:
  postgres_prod_data:

networks:
  quimio_network_prod:
    driver: bridge

  rede_externa:
    external: true
    name: quimioterapia_quimio_network
