version: '3.8'

services:
  db_aghu:
    image: postgres:15-alpine
    container_name: quimio_db_aghu
    volumes:
      - postgres_aghu_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_aghu
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db_aghu" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - quimio_network

  ldap:
    image: osixia/openldap:latest
    container_name: openldap_server
    environment:
      LDAP_ORGANISATION: "Hospital"
      LDAP_DOMAIN: "hc.gov.br"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_RFC2307BIS_SCHEMA: "true"
    volumes:
      - ./ldap_bootstrap:/container/service/slapd/assets/config/bootstrap/ldif/custom:Z
    ports:
      - "3389:389"
      - "3636:636"
    command: --copy-service
    networks:
      - quimio_network

  ldap-admin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8081:80"
    depends_on:
      - ldap
    networks:
      - quimio_network

volumes:
  postgres_aghu_data:

networks:
  quimio_network: {}